[project]
name = "bench_pixi"
version = "0.1.0"
description = "Benchmark for pixi"
authors = ["Ruben Arts <ruben@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]

bench = """
hyperfine --warmup 1 --runs 2  --export-markdown hyperfine.md --export-json hyperfine.json
--prepare 'rm pixi -rf'
 'pixi init -i mamba_env.yml pixi && pixi install --manifest-path pixi/pixi.toml' 
--prepare 'rm micromamba -rf'
 'micromamba create --file mamba_env.yml -p micromamba/.env --yes' 
--prepare 'rm conda -rf'
 'conda env create -f mamba_env.yml -p conda/.env'
"""
graph = "python graph.py"
start = {depends_on = ["bench", "graph"]}

[dependencies]
hyperfine = ">=1.18.0,<1.19"
micromamba = ">=2.0.5,<3"
conda = ">=24.11.2,<25"

# plotting
matplotlib = "*"
