[project]
name = "bench_pixi"
description = "Benchmark for pixi"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
bench = """
echo -----  Benchmark using $ENV_FILE -----;
hyperfine --warmup 1 --runs 3  --export-markdown hyperfine.md --export-json hyperfine.json --shell bash
--prepare 'rm -rf pixi'
 'pixi init -i $ENV_FILE pixi && cd pixi && pixi install'
--prepare 'rm -rf micromamba'
 'micromamba create --file $ENV_FILE -p micromamba/.env --yes'
--prepare 'rm -rf conda'
 'conda env create -f $ENV_FILE -p conda/.env'
"""

graph = "python graph.py"
chart = "python chart.py"
start = { depends-on = ["bench", "graph"] }

[feature.micro.activation.env]
ENV_FILE = "micro_env.yml"

[feature.dummy.activation.env]
ENV_FILE = "dummy_env.yml"

[feature.stress.activation.env]
ENV_FILE = "stress_env.yml"

[environments]
default = { features = ["micro"], solve-group = "default"}
dummy = { features = ["dummy"], solve-group = "default"}
stress = { features = ["stress"], solve-group = "default"}

[dependencies]
hyperfine = ">=1.19.0,<2"
micromamba = ">=2.0.5,<3"
conda = ">=25.1.1,<26"
matplotlib = ">=3.10.0,<4"
