name: Benchmark
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  bench-cached-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest, macos-13]
        pixi_version: [v0.39.2, v0.39.5, v0.40.0, v0.41.2]
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0
        with:
          pixi-version: ${{ matrix.pixi_version }}
          cache: false
      - run: |
          pixi run bench

      - name: Rename and Upload Benchmark Results
        run: |
          mv hyperfine.json ${{ matrix.os }}_${{ matrix.pixi_version }}_bench-results.json

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}_${{ matrix.pixi_version }}_benchmark-results
          path: ${{ matrix.os }}_${{ matrix.pixi_version }}_bench-results.json
