name: Benchmark
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  bench-cached-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest, macos-13]
        pixi_version: [v0.39.1, v0.41.2]
        environment: ["default", "dummy", "stress"]
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0
        with:
          pixi-version: ${{ matrix.pixi_version }}
          cache: true
          environment: ${{ matrix.environment }}
      - run: |
          pixi run bench
          echo "### ${{ matrix.os }} ${{ matrix.pixi_version }} ${{ matrix.environment }}" >> $GITHUB_STEP_SUMMARY
          pixi run chart >> $GITHUB_STEP_SUMMARY

      - name: Add summary to PR
        run: |
          cat hyperfine.md >> $GITHUB_STEP_SUMMARY

      - name: Rename and Upload Benchmark Results
        run: |
          mv hyperfine.json ${{ matrix.os }}_${{ matrix.pixi_version }}_${{ matrix.environment }}_bench-results.json
          mv hyperfine.md ${{ matrix.os }}_${{ matrix.pixi_version }}_${{ matrix.environment }}_bench-results.md

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}_${{ matrix.pixi_version }}_${{ matrix.environment }}_benchmark-results
          path: ${{ matrix.os }}_${{ matrix.pixi_version }}_${{ matrix.environment }}_bench-results.json

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}_${{ matrix.pixi_version }}_${{ matrix.environment }}_benchmark-markdown-results
          path: ${{ matrix.os }}_${{ matrix.pixi_version }}_${{ matrix.environment }}_bench-results.md
